### ISSUE TITLE
API change after 7/8? Null data json

### ISSUE THREAD

**Issue by kaustos** [apearson/southern-company-api#21]
(node:1564) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of null
    at SouthernCompanyAPI.<anonymous> (C:\scapi\node_modules\southern-company-api\dist\main.js:123:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\scapi\node_modules\southern-company-api\dist\main.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Line 123 is
            const matches = resData.data.html.match(regex);

Added some debug lines and the payload is null at [html]? Everything is null actually. Not sure what it should have looked like before.

```
{ statusCode: 200,
  message: null,
  data:
   { result: 0,
     token: '6%2bp97GxHMEtrFSuDj_redacted_long_token]',
     errorMessage: 'Login Succeeded.',
     messages: [],
     username: 'redacted_username',
     rememberUsername: null,
     staySignedIn: null,
     recaptchaResponse: null,
     targetPage: 0,
     params:
      { appBannerUrl: null,
        appTheme: null,
        appType: null,
        appID: null,
        returnUrl: 'null',
        cancelUrl: null,
        logonID: null,
        loginUrl: null,
        originalReturnUrl: null,
        origin: null,
        scWebToken: null,
        userID: null,
        addProfileLink: null,
        editProfileLink: null,
        forgotPasswordLink: null,
        forgotInfoLink: null,
        southerncoApplication: null,
        newUserHeaderText: null,
        newUserText: null,
        updateProfileText: null,
        forgotInfoText: null,
        emailValidationTicket: null,
        ticket: null,
        emailAddress: null,
        postTarget: null,
        compactDisplay: null,
        errorDisplayType: null,
        extendedIconVisible: null,
        extendedPopupEnabled: null,
        showLogin: null,
        noTokenReturnUrl: null,
        returnMethod: null,
        tokenEncoding: null,
        mfaConfigInternal: null,
        mfaConfigUnknown: null,
        mfaExcludeInternal: null,
        mfaExcludeUnknown: null,
        firstName: null,
        lastName: null,
        email: null,
        phoneNumber: null },
     html: null,
     redirect: null,
     origin: null },
  isSuccess: true,
  modelErrors: null }
```

**Comment by apearson** [comment]
I believe I resolved the issue, let me know if you're still having trouble!
