### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by insuusvenerati** [apearson/southern-company-api#24]
Is this still a valid method to get data from Southern Co? Been playing around with / debugging it a bit and mostly i'm just getting internal server errors.

**Comment by insuusvenerati** [comment]
Actually, after playing around with it, the current issue is getting a 403 forbidden on `monthlyData`

**Comment by apearson** [comment]
Just tested and `monthlyData` still works.  

Are you getting the `connected` event?  Any `error` events?

**Comment by insuusvenerati** [comment]
This is the message I get:
```
Connected...
Fetch Monthly Error FetchError: invalid json response body at https://customerservice2api.southerncompany.com/api/MyPowerUsage/MonthlyGraph/redacted reason: Unexpected end of JSON input
    at /mnt/misc/Code/gulf-power/.yarn/cache/node-fetch-npm-2.6.6-056db6b778-ee8290626b.zip/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0) {
  type: 'invalid-json'
}
Fetch Daily Error FetchError: invalid json response body at https://customerservice2api.southerncompany.com/api/MyPowerUsage/DailyGraph reason: Unexpected end of JSON input
    at /mnt/misc/Code/gulf-power/.yarn/cache/node-fetch-npm-2.6.6-056db6b778-ee8290626b.zip/node_modules/node-fetch/lib/index.js:273:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0) {
  type: 'invalid-json'
}
```
Using this from the docs.
```js
SouthernCompany.on("connected", () => {
  console.info("Connected...");

  async function fetchMonthly() {
    /* Getting Monthly Data */
    const monthlyData = await SouthernCompany.getMonthlyData();

    /* Printing Monthly Data */
    console.info("Monthly Data", JSON.stringify(monthlyData));
  }

  fetchMonthly().catch((error) => console.log("Fetch Monthly Error", error));

  async function fetchDaily() {
    /* Getting Daily Data */
    const startDate = new Date(2020, 2, 1);
    const endDate = new Date();
    const dailyData = await SouthernCompany.getDailyData(startDate, endDate);

    /* Printing daily data */
    console.info("Daily Data", JSON.stringify(dailyData));
  }

  fetchDaily().catch((error) => console.log("Fetch Daily Error", error));
});

/* Listening for any errors */
SouthernCompany.on("error", console.error);
```

**Comment by insuusvenerati** [comment]
This is where it fails:
```ts
    /* Waiting for all requests */
    const responses = await Promise.all(requests);

    /* Converting all responses to json */
    const resData: MonthlyDataResponse[] = await Promise.all(
      responses.map((response) => response.json()),
    );
```
In `resData`, `responses` ends up as an array containing the response:
```json
{
  "url": "https://customerservice2api.southerncompany.com/api/MyPowerUsage/MonthlyGraph/redacted",
  "status": 403,
  "statusText": "Forbidden",
  "headers": {},
  "counter": 0
}
```

**Comment by apearson** [comment]
Interesting, do you have the monthly graphs on the southern company website?

**Comment by insuusvenerati** [comment]
That's another weird thing but I figured it was a separate issue. I use gulfpower which I can login to fine. However, when I go to login on https://webauth.southernco.com/account/login, it just says Login Succeeded then hangs on Logging in forever.

**Comment by insuusvenerati** [comment]
Well, I think gulfpower is not part of southern company. At least not anymore. Assuming based on the options on https://customerservice2.southerncompany.com/Landing

**Comment by apearson** [comment]
Yup, that's the issue! Gulf Power was sold to another company and is now using a different backend.  Unfortunately this library doesn't support that different backend.

**Comment by insuusvenerati** [comment]
No worries. Thanks for taking a look

**Comment by apearson** [comment]
Anytime! Good luck!
